### ISSUE TITLE
Unsupported meshes bug: Index out of range with certain models

### ISSUE THREAD

**Issue by piXelicidio** [piXelicidio/DAPolyPaint#7]
Happens with samples from these sources after pressing START PAINT MODE: 
https://trockk.itch.io/new-td-turret-lot
https://assetstore.unity.com/packages/3d/animations/1h-swing-low-left-5785

**Comment by piXelicidio** [comment]
The root cause of the problem is overlapping vertices. The plugin should deal with them.

**Comment by mstergtr** [comment]
I am also having this problem with a Synty pack. Some models are fine while others are not.

**Comment by piXelicidio** [comment]
Hi @mstergtr , please if you could  grab to try the Painter.cs  script to replace in your project that would be of great help to confirm with more model samples.
https://github.com/piXelicidio/DAPolyPaint/blob/mesh-support/Painter.cs
I believe it solves most of the problems with this kind of meshes with overlapping vertices and other weird constructions. 
Thanks

**Comment by mstergtr** [comment]
The updated Painter script seems to have fixed the problem. Thanks! Great tool so far.
